[package]
name = "rashamon-ui"
version.workspace = true
edition.workspace = true

[features]
default = ["linux-desktop"]
linux-desktop = [
    "dep:drm-fourcc",
    "dep:libc",
    "dep:sdl2",
    "rashamon-renderer/webkit",
]
kamelot = ["rashamon-renderer/kamelot"]

[dependencies]
rashamon-ipc.workspace = true
rashamon-renderer = { workspace = true, default-features = false }
rashamon-net.workspace = true
memmap2.workspace = true
libc = { version = "0.2", optional = true }
drm-fourcc = { version = "2", optional = true }
sdl2 = { version = "0.35", optional = true }
rusttype = "0.9"
ab_glyph = "0.2"

[[bin]]
name = "rashamon-ui"
path = "src/main.rs"
